# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c3a5e4fec167bbcab999817fedcc611fe458212adad3337e81ace9b8307511b88d1391abe553159f9e335d1202aaac890bd907c1526dd735b518fabe88ba4c5

test:
  secret_key_base: 8a282322eb02cb64b39caa8ff94b1a04b5c03c645bf5856ed20342353561bbabaa3bd6b112bc97277b25d8ae324a9bc065d6028b7f012b4bacbfa0ceab45c9e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
